"""Public SDK for implementing out-of-process Campus AI connectors."""

from campus_connector_sdk.base import CampusConnector
from campus_connector_sdk.errors import ConnectorProtocolError
from campus_connector_sdk.models import (
    CONTRACT_VERSION,
    AuthChallenge,
    AuthChallengeField,
    AuthChallengeKind,
    AuthResult,
    AuthState,
    AuthStatusRequest,
    AttachmentAccess,
    AttachmentAccessMode,
    BeginAuthRequest,
    CampusAttachment,
    CampusItem,
    CampusItemBatch,
    CampusItemType,
    CampusPublisher,
    ConfigValidationRequest,
    ConfigValidationResult,
    ConnectorAttachment,
    ConnectorCapability,
    ConnectorErrorCode,
    ConnectorManifest,
    ConnectorMessage,
    SubmitAuthRequest,
    SyncWarning,
    SyncBatch,
    SyncRequest,
)
from campus_connector_sdk.service import create_connector_app

__all__ = [
    "CONTRACT_VERSION",
    "AuthChallenge",
    "AuthChallengeField",
    "AuthChallengeKind",
    "AuthResult",
    "AuthState",
    "AuthStatusRequest",
    "AttachmentAccess",
    "AttachmentAccessMode",
    "BeginAuthRequest",
    "CampusAttachment",
    "CampusConnector",
    "CampusItem",
    "CampusItemBatch",
    "CampusItemType",
    "CampusPublisher",
    "ConfigValidationRequest",
    "ConfigValidationResult",
    "ConnectorAttachment",
    "ConnectorCapability",
    "ConnectorErrorCode",
    "ConnectorManifest",
    "ConnectorMessage",
    "ConnectorProtocolError",
    "SubmitAuthRequest",
    "SyncWarning",
    "SyncBatch",
    "SyncRequest",
    "create_connector_app",
]
